import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import StoreProvider from "./StoreProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import { ThemeProvider } from "@mui/material/styles";
import theme from "../app/theme";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "./provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className=" bg-[url('/bg.png')] bg-cover bg-center bg-no-repeat bg-fixed">
        <div className="min-h-full flex flex-col backdrop-blur-2xl">
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <StoreProvider>
                <StyledComponentsRegistry>
                  <Providers>{children}</Providers>
                </StyledComponentsRegistry>
              </StoreProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </div>
      </body>
    </html>
  );
}
